export const initialState = {
  tasksListData: [
    {
      id: 1,
      todo: "Do something nice for someone I care about",
      completed: true,
      image: "https://robohash.org/hicveldicta.png",
      username: "atuny0",
    },
    {
      id: 2,
      todo: "Memorize the fifty states and their capitals",
      completed: false,
      image: "https://robohash.org/doloremquesintcorrupti.png",
      username: "hbingley1",
    },
    {
      id: 3,
      todo: "Watch a classic movie",
      completed: false,
      image: "https://robohash.org/consequunturautconsequatur.png",
      username: "rshawe2",
    },
    {
      id: 4,
      todo: "Contribute code or a monetary donation to an open-source software project",
      completed: false,
      image: "https://robohash.org/facilisdignissimosdolore.png",
      username: "yraigatt3",
    },
    {
      id: 5,
      todo: "Solve a Rubik's cube",
      completed: false,
      image: "https://robohash.org/adverovelit.png",
      username: "kmeus4",
    },
    {
      id: 6,
      todo: "Bake pastries for me and neighbor",
      completed: false,
      image: "https://robohash.org/laboriosamfacilisrem.png",
      username: "jtreleven5",
    },
    {
      id: 7,
      todo: "Go see a Broadway production",
      completed: false,
      image: "https://robohash.org/cupiditatererumquos.png",
      username: "dpettegre6",
    },
    {
      id: 8,
      todo: "Write a thank you letter to an influential person in my life",
      completed: true,
      image: "https://robohash.org/quiaharumsapiente.png",
      username: "ggude7",
    },
    {
      id: 9,
      todo: "Invite some friends over for a game night",
      completed: false,
      image: "https://robohash.org/excepturiiuremolestiae.png",
      username: "nloiterton8",
    },
    {
      id: 10,
      todo: "Have a football scrimmage with some friends",
      completed: false,
      image: "https://robohash.org/aliquamcumqueiure.png",
      username: "umcgourty9",
    },
    {
      id: 11,
      todo: "Text a friend I haven't talked to in a long time",
      completed: false,
      image: "https://robohash.org/impeditautest.png",
      username: "acharlota",
    },
    {
      id: 12,
      todo: "Organize pantry",
      completed: true,
      image: "https://robohash.org/namquaerataut.png",
      username: "rhallawellb",
    },
    {
      id: 13,
      todo: "Buy a new house decoration",
      completed: false,
      image: "https://robohash.org/voluptatemsintnulla.png",
      username: "lgribbinc",
    },
    {
      id: 14,
      todo: "Plan a vacation I've always wanted to take",
      completed: false,
      image: "https://robohash.org/quisequienim.png",
      username: "mturleyd",
    },
    {
      id: 15,
      todo: "Clean out car",
      completed: false,
      image: "https://robohash.org/autquiaut.png",
      username: "kminchelle",
    },
    {
      id: 16,
      todo: "Draw and color a Mandala",
      completed: true,
      image: "https://robohash.org/porronumquamid.png",
      username: "dpierrof",
    },
    {
      id: 17,
      todo: "Create a cookbook with favorite recipes",
      completed: false,
      image: "https://robohash.org/accusantiumvoluptateseos.png",
      username: "vcholdcroftg",
    },
    {
      id: 18,
      todo: "Bake a pie with some friends",
      completed: false,
      image: "https://robohash.org/nihilharumqui.png",
      username: "sberminghamh",
    },
    {
      id: 19,
      todo: "Create a compost pile",
      completed: true,
      image: "https://robohash.org/delenitipraesentiumvoluptatum.png",
      username: "bleveragei",
    },
    {
      id: 20,
      todo: "Take a hike at a local park",
      completed: true,
      image: "https://robohash.org/ipsumutofficiis.png",
      username: "aeatockj",
    },
    {
      id: 21,
      todo: "Take a class at local community center that interests you",
      completed: false,
      image: "https://robohash.org/providenttemporadelectus.png",
      username: "ckensleyk",
    },
    {
      id: 22,
      todo: "Research a topic interested in",
      completed: false,
      image: "https://robohash.org/temporarecusandaeest.png",
      username: "froachel",
    },
    {
      id: 23,
      todo: "Plan a trip to another country",
      completed: true,
      image: "https://robohash.org/odioquivero.png",
      username: "beykelhofm",
    },
    {
      id: 24,
      todo: "Improve touch typing",
      completed: false,
      image: "https://robohash.org/odiomolestiaealias.png",
      username: "brickeardn",
    },
    {
      id: 25,
      todo: "Learn Express.js",
      completed: false,
      image: "https://robohash.org/doloremautdolores.png",
      username: "dfundello",
    },
    {
      id: 26,
      todo: "Learn calligraphy",
      completed: false,
      image: "https://robohash.org/laboriosammollitiaut.png",
      username: "lgronaverp",
    },
    {
      id: 27,
      todo: "Have a photo session with some friends",
      completed: false,
      image: "https://robohash.org/nequeodiosapiente.png",
      username: "fokillq",
    },
    {
      id: 28,
      todo: "Go to the gym",
      completed: false,
      image: "https://robohash.org/consequunturabnon.png",
      username: "xisherwoodr",
    },
    {
      id: 29,
      todo: "Make own LEGO creation",
      completed: false,
      image: "https://robohash.org/amettemporeea.png",
      username: "jissetts",
    },
    {
      id: 30,
      todo: "Take cat on a walk",
      completed: false,
      image: "https://robohash.org/perferendisideveniet.png",
      username: "kdulyt",
    },
  ],
  newToDoObj: {
    id: null,
    todo: "",
    completed: false,
    image: "",
    username: "kdulyt",
  },
  isModalVisibile: false,
};
